# Generated by Django 4.0.5 on 2022-07-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_car_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuel',
            options={'ordering': ['-date_filled']},
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('type_oil', models.CharField(max_length=50)),
                ('miles_driven', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oils', to='car_app.car')),
            ],
            options={
                'ordering': ['-date_changed'],
            },
        ),
    ]
